import json
# id, label, type, options, routing (AUTO_OK = may become green when both readers agree; STUDENT; SPECIALIST), usual page types
F = []
def f(i, label, typ='text', opts=None, route='STUDENT', pages='admission sheet, progress notes', note=''):
    F.append(dict(id=i, label=label, type=typ, options=opts or [], route=route, usual_pages=pages, note=note))
YN = ['No', 'Yes']
f('A01', 'Patient name', route='AUTO_OK', pages='any page header')
f('A02', 'Age (years)', 'number', route='AUTO_OK', pages='admission sheet, header')
f('A03', 'Sex', 'option', ['Male', 'Female'], 'AUTO_OK', 'admission sheet, header')
f('A04', 'Residence / Address', route='AUTO_OK', pages='admission sheet, header')
f('A05', 'Occupation', route='AUTO_OK', pages='admission sheet')
f('A06', 'Visitor status', 'option', ['Pilgrim / Visitor', 'Local resident', 'Service worker / Volunteer', 'Unknown'], pages='admission sheet', note='Only if explicitly written; WR-003: documented Karbala residence -> Local resident (researcher convention; state it)')
f('A07', 'Level of consciousness at ICU admission', 'option', ['Conscious', 'DLOC', 'Unconscious'], pages='admission sheet, ICU admission note')
f('A08', 'Additional identification / notes (chart no., statistical no., register no.)', pages='any page header, register')
f('B01', 'Classification', 'option', ['Medical Emergency', 'Surgical Emergency', 'RTA', 'Post-op'], 'SPECIALIST', 'admission sheet, ICU admission note')
f('B02', 'Primary medical diagnosis (as documented; keep provisional/suspected/final apart)', route='SPECIALIST', pages='admission sheet, progress notes, discharge/death note')
f('B03', 'Primary surgical diagnosis', route='SPECIALIST', pages='admission sheet, operation note')
f('B04', 'Reason for ICU admission (as documented, verbatim)', pages='ICU admission note, referral note')
f('B05', 'If post-operative: type of operation / date', pages='operation note')
f('C01', 'ICU admission date (DD/MM/YYYY)', 'date', route='AUTO_OK', pages='ICU admission note, ICU register entry', note='Actual ICU admission, not ED/ward registration')
f('C02', 'ICU admission time', 'time', route='AUTO_OK', pages='ICU admission note, ICU register entry')
f('C03', 'Referral source', 'option', ['Direct admission', 'Emergency department', 'Other hospital', 'Other'], pages='admission sheet, ICU admission note')
f('C04', 'Early referral', 'option', ['Yes', 'No', 'Unknown'], 'SPECIALIST', 'admission sheet', note='Definition pending (§15.5): report the documented facts only')
f('C05', 'Presenting event / history leading to ICU admission', pages='admission sheet, ICU admission note')
f('D01', 'Vasopressors required', 'option', YN, 'AUTO_OK', 'drug/medication chart, progress notes', note='"Yes" only with drug/date; "No" only if the chart says so')
f('D02', 'Vasopressor agents', 'multi', ['Norepinephrine', 'Epinephrine', 'Dopamine', 'Vasopressin', 'Other'], 'AUTO_OK', 'drug/medication chart')
f('D03', 'Mechanical ventilation required', 'option', YN, 'AUTO_OK', 'ventilator chart, progress notes, nursing sheet')
f('D04', 'Mechanical ventilation duration (days)', 'number', pages='ventilator chart, progress notes')
f('D05', 'Trial to extubate', 'option', YN, pages='progress notes, ventilator chart')
f('D06', 'Extubation status (as documented)', pages='progress notes')
f('D07', 'Tracheostomy (and date)', 'option', YN, 'AUTO_OK', 'progress notes, operation note')
f('D08', 'Tracheostomy indication', route='SPECIALIST', pages='progress notes')
f('D09', 'CRRT indication', 'multi', ['AKI', 'Severe electrolyte disturbance', 'Metabolic acidosis', 'Fluid overload', 'Hemodynamic instability', 'Other'], 'SPECIALIST', 'progress notes, dialysis record')
f('D10', 'CRRT duration', pages='dialysis record, progress notes')
f('D11', 'NG feeding', 'option', YN, 'AUTO_OK', 'nursing sheet, progress notes, drug chart')
for k, (i, lab) in enumerate([('E01', 'E'), ('E02', 'V'), ('E03', 'M')]):
    f(i, f'GCS at ICU admission — {lab} component', 'number', route='AUTO_OK', pages='ICU admission note, flow sheet, nursing sheet', note='Clearly timed at/near ICU admission. Keep V=T. A later GCS is not admission GCS.')
f('E04', 'GCS at ICU admission — total as written (e.g. "15/15")', pages='ICU admission note', note='Only a total written in the chart; never compute one')
for i, lab in [('E05', 'E'), ('E06', 'V'), ('E07', 'M')]:
    f(i, f'GCS at ICU discharge / final assessment — {lab} component', 'number', pages='progress notes, discharge/death note, flow sheet')
f('E08', 'GCS at ICU discharge / final — total as written', pages='progress notes, discharge note')
f('F01', 'PMH / chronic diseases', 'multi', ['None', 'DM', 'HTN', 'IHD', 'Heart failure', 'CKD', 'COPD', 'Asthma', 'Liver disease', 'Neurological disease', 'Malignancy', 'Other'], 'AUTO_OK', 'admission sheet, ICU admission note', note='"None" only if the chart says so (e.g. "no PMH", "free")')
f('F02', 'Other comorbidities / details', pages='admission sheet')
f('F03', 'PSH', 'option', ['No previous operation', 'Previous operation'], pages='admission sheet')
f('F04', 'PSH — type of operation', pages='admission sheet')
f('G01', 'Drug history (home medications)', pages='admission sheet')
f('G02', 'Drug allergy', 'option', YN, 'AUTO_OK', 'admission sheet, drug chart', note='"No" only for explicit "NKDA"/"no known drug allergy"')
f('G03', 'Drug allergy — drug / reaction', pages='admission sheet, drug chart')
f('H01', 'Anemia present', 'option', ['No', 'Yes', 'Unknown'], 'SPECIALIST', 'lab reports', note='Threshold pending (§15.4): report Hb facts only')
f('H02', 'Hb on ICU admission (g/dL)', 'number', route='AUTO_OK', pages='lab reports, ABG slips', note='Within the admission window only; give time')
f('H03', 'Blood (RBC) transfused', 'option', YN, 'AUTO_OK', 'drug chart, progress notes, nursing sheet')
f('H04', 'Blood — number of units', 'number', route='AUTO_OK', pages='drug chart, progress notes')
f('H05', 'Blood — reason', 'multi', ['Anemia', 'Active bleeding', 'Perioperative requirement', 'Other'], pages='progress notes')
f('H06', 'Plasma transfused', 'option', YN, pages='drug chart, progress notes')
f('H07', 'Plasma — number of units', 'number', pages='drug chart, progress notes')
f('H08', 'Plasma — reason', 'multi', ['Coagulopathy', 'Active bleeding', 'Massive transfusion', 'Perioperative', 'Other'], pages='progress notes')
f('H09', 'Other blood products', 'multi', ['Cryoprecipitate', 'Platelets', 'FFP', 'Albumin', 'Other'], pages='drug chart')
f('H10', 'Other cost-related resources / transfusions', pages='drug chart, progress notes')
f('I01', 'Bed sore / pressure ulcer', 'option', YN, pages='nursing sheet, progress notes')
f('I02', 'Bed sore present on admission', 'option', ['Yes', 'No'], pages='nursing sheet')
f('I03', 'Bed sore developed during ICU stay', 'option', ['Yes', 'No'], pages='nursing sheet')
f('I04', 'Bed sore site / stage', pages='nursing sheet')
f('I05', 'Upper GI bleeding', 'option', ['No', 'Yes', 'Suspected'], pages='progress notes')
f('I06', 'UGIB — required OGD', 'option', ['Yes', 'No', 'Conservative treatment'], pages='progress notes')
f('I07', 'UGIB — required blood transfusion', 'option', YN, pages='progress notes')
f('I08', 'Other ICU complications', 'multi', ['Ventilator-associated pneumonia', 'Septic shock', 'AKI', 'Acute respiratory failure', 'Arrhythmia', 'DVT/PE', 'Electrolyte disturbance', 'Multi-organ failure', 'Other'], 'SPECIALIST', 'progress notes, lab reports')
f('I09', 'Complications — details, dates, severity', route='SPECIALIST', pages='progress notes')
f('J01', 'Final ICU outcome', 'option', ['Death', 'Transferred to Medical Ward', 'Transferred to Surgical Ward', 'DAMA', 'Transferred to Another Hospital'], 'AUTO_OK', 'discharge/death note, progress notes, ICU register')
f('J02', 'Date of outcome (DD/MM/YYYY)', 'date', route='AUTO_OK', pages='discharge/death note, ICU register')
f('J03', 'Outcome details / destination / reason', pages='discharge/death note')
f('K01', 'Immediate / primary cause of death', route='SPECIALIST', pages='death note', note='NOT_APPLICABLE only if J01 is FOUND as a non-death outcome')
f('K02', 'If cardiac arrest — underlying cause', route='SPECIALIST', pages='death note')
f('K03', 'Date / time of death', 'datetime', route='AUTO_OK', pages='death note')
f('K04', 'Clinical sequence leading to death / contributing causes', route='SPECIALIST', pages='death note, progress notes')
for i, lab in [('L01', 'Temperature (°C)'), ('L02', 'Mean arterial pressure, or SBP/DBP (mmHg)'), ('L03', 'Heart rate (/min)'), ('L04', 'Respiratory rate (/min)'),
               ('L05', 'Oxygenation: FiO2 with PaO2 (and PaCO2)'), ('L06', 'Arterial pH'), ('L07', 'Serum Na (mmol/L)'), ('L08', 'Serum K (mmol/L)'),
               ('L09', 'Serum creatinine (state unit; note any AKI statement)'), ('L10', 'Hematocrit (%)'), ('L11', 'WBC (x10^3/uL)'), ('L12', 'GCS used for APACHE (E/V/M)')]:
    f(i, 'APACHE II raw value — ' + lab, 'apache', route='AUTO_OK', pages='flow sheet, lab reports, ABG slips, nursing sheet',
      note='List EVERY value found in the first 24 h after ICU admission, each with its time. Never mix times. Never substitute SpO2 for PaO2.')
f('L13', 'APACHE II — chronic health points (documented severe organ insufficiency / immunocompromise)', route='SPECIALIST', pages='admission sheet')
f('L14', 'APACHE II total as written in the chart (if any)', 'number', pages='admission sheet, flow sheet', note='Only if the chart itself writes an APACHE score')
json.dump(F, open(__import__('sys').argv[1], 'w'), ensure_ascii=False, indent=1)
print(len(F), 'fields')
