services:
  backend:
    image: marley-demo:v16
    pull_policy: never

  configurator:
    image: marley-demo:v16
    pull_policy: never

  create-site:
    image: marley-demo:v16
    pull_policy: never
    command:
      - >
        wait-for-it -t 180 db:3306;
        wait-for-it -t 180 redis-cache:6379;
        wait-for-it -t 180 redis-queue:6379;
        export start=$$(date +%s);
        until [[ -n $$(grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty") ]] &&
          [[ -n $$(grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty") ]] &&
          [[ -n $$(grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty") ]];
        do
          echo "Waiting for sites/common_site_config.json";
          sleep 5;
          if (( $$(date +%s)-start > 180 )); then
            echo "common_site_config.json was not ready in time";
            exit 1;
          fi;
        done;
        if [ ! -d "sites/frontend" ]; then
          bench new-site
          --mariadb-user-host-login-scope='%'
          --admin-password=admin
          --db-root-username=root
          --db-root-password=admin
          --set-default frontend;
        else
          bench use frontend;
        fi;
        bench --site frontend list-apps | grep -qx erpnext ||
          bench --site frontend install-app erpnext;
        bench --site frontend list-apps | grep -qx healthcare ||
          bench --site frontend install-app healthcare;
        bench --site frontend list-apps | grep -qx marley_frontend ||
          bench --site frontend install-app marley_frontend;
        bench --site frontend migrate;
        bench --site frontend set-config developer_mode 1;
        echo "All Marley demo apps are installed.";

  frontend:
    image: marley-demo:v16
    pull_policy: never

  queue-long:
    image: marley-demo:v16
    pull_policy: never

  queue-short:
    image: marley-demo:v16
    pull_policy: never

  scheduler:
    image: marley-demo:v16
    pull_policy: never

  websocket:
    image: marley-demo:v16
    pull_policy: never
